#ALIYAN ALI
# sp22-bcs-035
# Mid lab

In [3]:
import numpy as np

def row_echelon(matrix):
    mat = matrix.astype(float)
    rows, cols = mat.shape
    lead = 0

    for r in range(rows):
        if lead >= cols:
            return mat
        i = r
        while mat[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if cols == lead:
                    return mat
        # Swap rows
        mat[[i, r]] = mat[[r, i]]

        # Normalize the pivot row
        lv = mat[r, lead]
        mat[r] = mat[r] / lv

        # Eliminate below
        for i in range(r + 1, rows):
            lv = mat[i, lead]
            mat[i] = mat[i] - lv * mat[r]
        lead += 1
    return mat

# Example 4x4 matrix
A = np.array([
    [2, 1, -1, 3],
    [4, 2, 1, 1],
    [-2, 1, 3, 2],
    [6, 2, -2, -1]
], dtype=float)

print("Original Matrix:")
print(A)

ref_matrix = row_echelon(A)
print("\nRow Echelon Form:")
print(ref_matrix)


Original Matrix:
[[ 2.  1. -1.  3.]
 [ 4.  2.  1.  1.]
 [-2.  1.  3.  2.]
 [ 6.  2. -2. -1.]]

Row Echelon Form:
[[ 1.          0.5        -0.5         1.5       ]
 [ 0.          1.          1.          2.5       ]
 [ 0.          0.          1.         -1.66666667]
 [-0.         -0.         -0.          1.        ]]
